Automated import of osximg 0.5.0

diff --git a/osximg b/osximg
--- a/osximg
+++ b/osximg
@@ -1,6 +1,9 @@
 #!/bin/bash
 # osximg - create bootable disk images from Mac OS X install files
 #
+# Version 0.5.0 (2014-04-30)
+# Add automatic system version detection, remove -t. Improve file handling.
+#
 # Version 0.4.2 (2014-04-30)
 # Refactor target system version argument handling. Cosmetics.
 #
@@ -26,26 +29,25 @@ SELF="$0"
 SELF_NAME=$(basename "$SELF")
 
 # Defaults
+APP_OSX109="Install OS X Mavericks.app"
+APP_OSX108="Install OS X Mountain Lion.app"
+APP_OSX107="Install Mac OS X Lion.app"
 ATTACH=false
 FORMAT="iso"
-SOURCE=""
 OUTPUT=""
-VERS="osx109"
+SOURCE=""
+VERS=""
 HELP="\
 usage: $SELF_NAME [-hv]
-       $SELF_NAME source -o path [-a] [-f format] [-t version]
+       $SELF_NAME source -o path [-a] [-f format]
 where:
    -h  display this help text
    -v  display version information
    -a  attach/mount final image when complete
    -f  specify format/method -- iso (default), apple (createinstallmedia 10.9+)
-   -o  specify output path
-   -t  specify target system version --
-         Mavericks      (osx109)
-         Mountain Lion  (osx108)
-         Lion           (osx107)"
+   -o  specify output path"
 VERSION="\
-osximg 0.4.2"
+osximg 0.5.0"
 
 # Get source path
 if [[ "$#" -gt 0 ]] && [[ ! "${1:0:1}" = "-" ]]; then
@@ -53,7 +55,7 @@ if [[ "$#" -gt 0 ]] && [[ ! "${1:0:1}" = "-" ]]; then
     shift 1
 fi
 
-# Super users only, except when printing help or version information
+# Super user only, except when printing help or version information
 SUID=$(id -u root)
 if [[ "$UID" != "$SUID" ]] && ( [[ "$#" -eq 0 ]] || grep -qv '^-\(h\|v\)' <<< "$1" ); then
     ERROR="$SELF_NAME: cannot run as normal user, try sudo"
@@ -62,7 +64,7 @@ if [[ "$UID" != "$SUID" ]] && ( [[ "$#" -eq 0 ]] || grep -qv '^-\(h\|v\)' <<< "$
 fi
 
 # Handle arguments
-while getopts ":af:ho:t:v" OPT
+while getopts ":af:ho:v" OPT
 do
     case "${OPT}"
     in
@@ -89,37 +91,6 @@ do
         o)
             # Output path
             OUTPUT="$OPTARG"
-            ;;
-        t)
-            # Target system version
-            VERS="$OPTARG"
-            case "$VERS"
-            in
-                "osx109"|"Mavericks")
-                    VERS="osx109"
-                    APP="Install OS X Mavericks.app"
-                    CIM="$SOURCE/Contents/Resources/createinstallmedia"
-                    CIM_MOUNT="/Volumes/Install OS X Mavericks"
-                    IESD="$SOURCE/Contents/SharedSupport/InstallESD.dmg"
-                    ;;
-                "osx108"|"Mountain Lion")
-                    VERS="osx108"
-                    APP="Install OS X Mountain Lion.app"
-                    IESD="$SOURCE/Contents/SharedSupport/InstallESD.dmg"
-                    ;;
-                "osx107"|"Lion")
-                    VERS="osx107"
-                    APP="Install Mac OS X Lion.app"
-                    IESD="$SOURCE/Contents/SharedSupport/InstallESD.dmg"
-                    ;;
-                *)
-                    # Invalid option specified
-                    ERROR="$SELF_NAME: invalid option for -t: $OPTARG"
-                    echo "$ERROR" >&2 && syslog -s -l error "$ERROR"
-                    echo -e "$HELP"
-                    exit 1
-                    ;;
-            esac
             ;;
         v)
             # Print version and exit
@@ -160,25 +131,46 @@ if [[ "$SOURCE" == "" ]]; then
     echo "$ERROR" >&2 && syslog -s -l error "$ERROR"
     echo -e "$HELP"
     exit 1
-elif [[ ! -e "$SOURCE" ]]; then
-    # Source path does not exist
-    ERROR="$SELF_NAME: source path does not exist: $SOURCE"
-    echo "$ERROR" >&2 && syslog -s -l error "$ERROR"
-    echo -e "$HELP"
-    exit 1
 elif [[ "$OUTPUT" == "" ]]; then
     # Output path not specified
     ERROR="$SELF_NAME: output path not specified"
     echo "$ERROR" >&2 && syslog -s -l error "$ERROR"
     echo -e "$HELP"
     exit 1
+elif [[ ! -e "$SOURCE" ]]; then
+    # Source path does not exist
+    ERROR="$SELF_NAME: source path does not exist: $SOURCE"
+    echo "$ERROR" >&2 && syslog -s -l error "$ERROR"
+    exit 1
 elif [[ -e "$OUTPUT" ]]; then
     # Output path already exists
     ERROR="$SELF_NAME: output path already exists: $OUTPUT"
     echo "$ERROR" >&2 && syslog -s -l error "$ERROR"
-    echo -e "$HELP"
     exit 1
 fi
+
+# Function to create temporary files
+function make_temp {
+
+    # Use output path as location
+    TEMP=$(mktemp -d "$OUTPUT Temporary Files XXXXXX")
+
+}
+
+# Function to remove temporary files
+function remove_temp {
+
+    # Unmount all temporary file systems and remove temporary files
+    if [[ "$TEMP" != "" ]] && [[ -e "$TEMP" ]]; then
+        set +e
+        hdiutil detach "$TEMP/*.mount" -quiet
+        sleep 2
+        hdiutil detach "$TEMP/*.mount" -force -quiet
+        sleep 1
+        rm -rf "$TEMP"
+    fi
+
+}
 
 # Function for Mac OS X 10.9 Mavericks, ISO/HFS hybrid bootable
 function make_osx109_iso {
@@ -188,9 +180,9 @@ function make_osx109_iso {
 
     # Create temporary image
     echo "Creating temporary image..."
-    hdiutil convert "$IESD_MOUNT/BaseSystem.dmg" -o "$IMAGE" -format UDSB -quiet
-    hdiutil resize "$IMAGE" -size 6g -quiet
-    hdiutil attach "$IMAGE" -mountpoint "$IMAGE_MOUNT" -owners on -nobrowse -quiet
+    hdiutil convert "$IESD_MOUNT/BaseSystem.dmg" -o "$IMAGE.sparsebundle" -format UDSB -quiet
+    hdiutil resize "$IMAGE.sparsebundle" -size 6g -quiet
+    hdiutil attach "$IMAGE.sparsebundle" -mountpoint "$IMAGE_MOUNT" -owners on -nobrowse -quiet
 
     # Copy system packages
     echo "Copying system packages..."
@@ -203,11 +195,14 @@ function make_osx109_iso {
 
     # Shrink
     echo "Shrinking image..."
-    hdiutil resize -quiet -size min "$IMAGE"
+    hdiutil resize -quiet -size min "$IMAGE.sparsebundle"
 
     # Save final image
     echo "Saving final image..."
-    hdiutil makehybrid "$IMAGE" -o "$OUTPUT" -hfs -iso -quiet
+    hdiutil makehybrid "$IMAGE.sparsebundle" -o "$IMAGE.iso" -hfs -iso -quiet
+
+    # Rename target
+    mv "$IMAGE.iso" "$OUTPUT"
 
 }
 
@@ -215,6 +210,7 @@ function make_osx109_iso {
 function make_osx109_apple {
 
     # Eject potentially conflicting volume
+    CIM_MOUNT="/Volumes/Install OS X Mavericks"
     if [[ -e "$CIM_MOUNT" ]]; then
         hdiutil detach "$CIM_MOUNT" -quiet
         echo "Ejected already mounted volume $CIM_MOUNT to avoid conflicts."
@@ -222,20 +218,20 @@ function make_osx109_apple {
 
     # Create temporary image and run createinstallmedia tool
     echo "Creating temporary image..."
-    hdiutil create "$IMAGE" -fs HFS+ -size 8g -type SPARSEBUNDLE -nospotlight -quiet
-    hdiutil attach "$IMAGE" -mountpoint "$IMAGE_MOUNT" -nobrowse -noverify -quiet
-    "$CIM" --nointeraction --applicationpath "$SOURCE" --volume "$IMAGE_MOUNT" | grep -v --line-buffered '^\(Done\.\|Copy complete\.\)$'
+    hdiutil create "$IMAGE.sparsebundle" -fs HFS+ -size 8g -type SPARSEBUNDLE -nospotlight -quiet
+    hdiutil attach "$IMAGE.sparsebundle" -mountpoint "$IMAGE_MOUNT" -nobrowse -noverify -quiet
+    "$SOURCE/Contents/Resources/createinstallmedia" --nointeraction --applicationpath "$SOURCE" --volume "$IMAGE_MOUNT" | grep -v --line-buffered '^\(Done\.\|Copy complete\.\)$'
 
     # Eject source volume
-    hdiutil detach -quiet "$CIM_MOUNT"
+    hdiutil detach "$CIM_MOUNT" -quiet
 
     # Shrink
     echo "Shrinking image..."
-    hdiutil resize "$IMAGE" -size min -quiet
+    hdiutil resize "$IMAGE.sparsebundle" -size min -quiet
 
     # Save final image
     echo "Saving final image..."
-    hdiutil convert "$IMAGE" -o "$IMAGE.cdr" -format UDTO -quiet
+    hdiutil convert "$IMAGE.sparsebundle" -o "$IMAGE.cdr" -format UDTO -quiet
 
     # Rename target
     mv "$IMAGE.cdr" "$OUTPUT"
@@ -247,7 +243,10 @@ function make_osx108_iso {
 
     # Save final image
     echo "Saving final image..."
-    hdiutil makehybrid "$IESD" -o "$OUTPUT" -hfs -iso -quiet
+    hdiutil makehybrid "$IESD" -o "$IMAGE.iso" -hfs -iso -quiet
+
+    # Rename target
+    mv "$IMAGE.iso" "$OUTPUT"
 
 }
 
@@ -256,98 +255,79 @@ function make_osx107_iso {
 
     # Save final image
     echo "Saving final image..."
-    hdiutil makehybrid "$IESD" -o "$OUTPUT" -hfs -iso -quiet
+    hdiutil makehybrid "$IESD" -o "$IMAGE.iso" -hfs -iso -quiet
+
+    # Rename target
+    mv "$IMAGE.iso" "$OUTPUT"
 
 }
 
-# Validate format
-if [[ "$FORMAT" == "apple" ]] && [[ "$VERS" != "osx109" ]]; then
-    # Format not supported
-    ERROR="$SELF_NAME: format '$FORMAT' (createinstallmedia) not supported for target system versions prior to Mac OS X 10.9 Mavericks"
-    echo "$ERROR" >&2 && syslog -s -l error "$ERROR"
-    echo -e "$HELP"
-    exit 1
-fi
+# Make temporary directory
+make_temp
 
-# Validate source
-SOURCE_VALID=false
-CIM="${CIM:-}"
-if hdiutil imageinfo -format "$IESD" >/dev/null 2>&1 && ( [[ "$CIM" == "" ]] || [[ -e "$CIM" ]] ); then
-    # Got app bundle, image located
-    # CIM located or not needed
-    SOURCE_VALID=true;
-elif hdiutil imageinfo -format "$SOURCE" >/dev/null 2>&1 && [[ "$CIM" == "" ]]; then
+# Make temporary files
+OUTPUT_NAME=$(basename "$OUTPUT")
+IMAGE="$TEMP/$OUTPUT_NAME"
+IMAGE_MOUNT="$TEMP/$OUTPUT_NAME.temp.mount"
+IESD_MOUNT="$TEMP/$OUTPUT_NAME.installesd.mount"
+BASE_MOUNT="$TEMP/$OUTPUT_NAME.basesystem.mount"
+
+# Detect source version
+IESD="$SOURCE/Contents/SharedSupport/InstallESD.dmg"
+if ! hdiutil imageinfo -format "$IESD" >/dev/null 2>&1 && hdiutil imageinfo -format "$SOURCE" >/dev/null 2>&1; then
     # Got image
-    SOURCE_VALID=true;
     IESD="$SOURCE"
 fi
-
-if $SOURCE_VALID; then
-
-    # Create temporary directories
-    OUTPUT_NAME=$(basename "$OUTPUT")
-    TEMP=$(mktemp -d "$OUTPUT Temporary Files XXXXXX")
-    IMAGE="$TEMP/$OUTPUT_NAME.sparsebundle"
-    IMAGE_MOUNT="$TEMP/$OUTPUT_NAME.sparsebundle.mount"
-    IESD_MOUNT="$TEMP/$OUTPUT_NAME.installesd.mount"
-    BASE_MOUNT="$TEMP/$OUTPUT_NAME.basesystem.mount"
-
-    # Validate source version
-    SOURCE_VERSION_VALID=false
-    echo "Verifying source..."
-    if hdiutil attach "$IESD" -mountpoint "$IESD_MOUNT" -nobrowse -quiet; then
-        # Image attached
-        if [[ "$VERS" == "osx109" ]]; then
-            if [[ -e "$IESD_MOUNT/BaseSystem.dmg" ]] && [[ -e "$IESD_MOUNT/Packages" ]]; then
-                # Structure seems normal, base system found
-                if hdiutil attach "$IESD_MOUNT/BaseSystem.dmg" -mountpoint "$BASE_MOUNT" -nobrowse -quiet; then
-                    # Base system attached
-                    if [[ -e "$BASE_MOUNT/$APP" ]]; then
-                        # Reasonably certain version is valid
-                        SOURCE_VERSION_VALID=true
-                    fi
-                    hdiutil detach "$BASE_MOUNT" -quiet
-                fi
-            fi
-        else
-            if [[ -e "$IESD_MOUNT/$APP" ]]; then
-                # Reasonably certain version is valid
-                SOURCE_VERSION_VALID=true
-            fi
-        fi
-        hdiutil detach "$IESD_MOUNT" -quiet
-    fi
-
-    if $SOURCE_VERSION_VALID; then
-
-        make_"$VERS"_"$FORMAT"
-
-        # Attach final image
-        if $ATTACH; then
-            echo "Attaching..."
-            hdiutil attach "$OUTPUT" -autoopen -verify -quiet
-        fi
-
+if hdiutil attach "$IESD" -mountpoint "$IESD_MOUNT" -nobrowse -quiet; then
+    # Image attached
+    if [[ -e "$IESD_MOUNT/$APP_OSX107" ]]; then
+        # Got Lion
+        echo "Mac OS X 10.7 Lion detected."
+        VERS="osx107"
+    elif [[ -e "$IESD_MOUNT/$APP_OSX108" ]]; then
+        # Got Mountain Lion
+        echo "Mac OS X 10.8 Mountain Lion detected."
+        VERS="osx108"
     else
-        # Source invalid
-        rm -rf "$TEMP"
-        ERROR="$SELF_NAME: invalid source version"
-        echo "$ERROR" >&2 && syslog -s -l error "$ERROR"
-        echo -e "$HELP"
-        exit 1
+        if hdiutil attach "$IESD_MOUNT/BaseSystem.dmg" -mountpoint "$BASE_MOUNT" -nobrowse -quiet; then
+            if [[ -e "$BASE_MOUNT/$APP_OSX109" ]] && [[ -e "$SOURCE/Contents/Resources/createinstallmedia" ]]; then
+                # Got Mavericks
+                echo "Mac OS X 10.9 Mavericks detected."
+                VERS="osx109"
+            fi
+            hdiutil detach "$BASE_MOUNT" -quiet
+        fi
     fi
+    hdiutil detach "$IESD_MOUNT" -quiet
+fi
 
-    # Clean
-    echo "Cleaning up..."
-    rm -rf "$TEMP"
-
-else
-    # Source invalid
-    ERROR="$SELF_NAME: invalid source"
+# Validate version and format
+if [[ "$VERS" == "" ]]; then
+    # Source invalid or version not supported
+    remove_temp
+    ERROR="$SELF_NAME: source invalid or version not supported"
     echo "$ERROR" >&2 && syslog -s -l error "$ERROR"
-    echo -e "$HELP"
+    exit 1
+elif [[ "$FORMAT" == "apple" ]] && [[ "$VERS" != "osx109" ]]; then
+    # Format not supported
+    remove_temp
+    ERROR="$SELF_NAME: format '$FORMAT' (createinstallmedia) not supported for target system versions prior to Mac OS X 10.9 Mavericks"
+    echo "$ERROR" >&2 && syslog -s -l error "$ERROR"
     exit 1
 fi
+
+# Build image
+make_"$VERS"_"$FORMAT"
+
+# Attach final image
+if $ATTACH; then
+    echo "Attaching..."
+    hdiutil attach "$OUTPUT" -autoopen -verify -quiet
+fi
+
+# Remove temporary files
+echo "Cleaning up..."
+remove_temp
 
 # Done
 echo "Done."
